# Generated by Django 5.2.10 on 2026-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
    ]
