# Generated by Django 5.2.10 on 2026-01-25 17:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_amount_paid_loan_duration_months_loan_emis_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-applied_at']},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='identity_proof',
        ),
        migrations.AddField(
            model_name='loan',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/aadhaar/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='application_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='application_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='application_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_statements',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/bank/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='cibil_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='documents_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='employment_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/employment/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='employment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='encumbrance_clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='existing_emi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='final_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='final_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='foir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='legal_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='legal_documents',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/legal/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='legal_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='legal_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='legal_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_agreement',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/agreement/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan'), ('VEHICLE', 'Vehicle Loan'), ('BUSINESS', 'Business Loan'), ('EDUCATION', 'Education Loan')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='ltv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/pan/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='residence_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='salary_slips',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/salary/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='sanction_letter',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/sanction/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='title_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPLICATION_REVIEW', 'Under Application Review'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('CREDIT_REVIEW', 'Under Credit Review'), ('CREDIT_APPROVED', 'Credit Approved'), ('CREDIT_REJECTED', 'Credit Rejected'), ('LEGAL_REVIEW', 'Under Legal Review'), ('LEGAL_APPROVED', 'Legal Approved'), ('LEGAL_REJECTED', 'Legal Rejected'), ('FINAL_REVIEW', 'Final Review'), ('APPROVED', 'Loan Approved'), ('REJECTED', 'Loan Rejected'), ('DISBURSED', 'Disbursed'), ('PAID', 'Fully Paid')], default='DRAFT', max_length=25),
        ),
    ]
