# Generated by Django 5.2.10 on 2026-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Customer'), ('APPLICATION_OFFICER', 'Customer Acquisition & Application Officer'), ('CREDIT_OFFICER', 'Credit, Risk & Verification Officer'), ('LEGAL_OFFICER', 'Technical & Legal Evaluation Officer'), ('DISBURSEMENT_MANAGER', 'Approval, Documentation & Disbursement Manager')], default='USER', max_length=25),
        ),
    ]
